# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5

# optionally specify a list of environments, for example to test different RDBMS
env:
  - example=example

install:
  - composer install --prefer-source --no-interaction

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - echo "Inicio"
  - mkdir /home/travis/build/ricardovroma/teste_php/myapp/protected/runtime

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
  - phpunit tests/palindromo_test.php
  - phpunit --configuration myapp/protected/tests/phpunit.xml --coverage-text


# configure notifications (email, IRC, campfire etc)
notifications: